version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: project_management
      POSTGRES_USER: pm_user
      POSTGRES_PASSWORD: pm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: